/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MenuList: typeof import('./src/components/operation-panel/components/menu-list.vue')['default']
    MenuPanel: typeof import('./src/components/menu-panel/index.vue')['default']
    OperationPanel: typeof import('./src/components/operation-panel/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
